import type { MathRule } from "../types";

export const MATH_RULES: MathRule[] = [
  {
    id: "sym/star-to-times",
    group: "sym",
    descriptionKey: "rule.sym/star-to-times",
    pattern: /\*/g,
    replacement: " \\times ",
    enabled: false,
  },
  {
    id: "sym/less-equal",
    group: "sym",
    descriptionKey: "rule.sym/less-equal",
    pattern: /<=/g,
    replacement: " \\le ",
    enabled: true,
  },
  {
    id: "sym/greater-equal",
    group: "sym",
    descriptionKey: "rule.sym/greater-equal",
    pattern: />=/g,
    replacement: " \\ge ",
    enabled: true,
  },
  {
    id: "sym/not-equal",
    group: "sym",
    descriptionKey: "rule.sym/not-equal",
    pattern: /!=/g,
    replacement: " \\neq ",
    enabled: true,
  },
  {
    id: "sym/double-equal-to-single",
    group: "sym",
    descriptionKey: "rule.sym/double-equal-to-single",
    pattern: /==/g,
    replacement: " = ",
    enabled: false,
  },
  {
    id: "sym/arrow-right-to",
    group: "sym",
    descriptionKey: "rule.sym/arrow-right-to",
    pattern: /-+>/g,
    replacement: " \\to ",
    enabled: true,
  },
  {
    id: "sym/arrow-left-gets",
    group: "sym",
    descriptionKey: "rule.sym/arrow-left-gets",
    pattern: /<-+/g,
    replacement: " \\gets ",
    enabled: true,
  },
  {
    id: "sym/double-arrow-implies",
    group: "sym",
    descriptionKey: "rule.sym/double-arrow-implies",
    pattern: /=+>/g,
    replacement: " \\Rightarrow ",
    enabled: true,
  },
  {
    id: "sym/mod",
    group: "sym",
    descriptionKey: "rule.sym/mod",
    pattern: /(?<![\\%a-zA-Z])%(?![a-zA-Z])/g,
    replacement: " \\bmod ",
    enabled: true,
  },
  {
    id: "sym/left-shift",
    group: "sym",
    descriptionKey: "rule.sym/left-shift",
    pattern: /<<(?!=)/g,
    replacement: " \\ll ",
    enabled: true,
  },
  {
    id: "sym/right-shift",
    group: "sym",
    descriptionKey: "rule.sym/right-shift",
    pattern: />>(?!=)/g,
    replacement: " \\gg ",
    enabled: true,
  },
  {
    id: "sym/bitwise-and",
    group: "sym",
    descriptionKey: "rule.sym/bitwise-and",
    pattern: /(?<![&\\])&(?![&=])/g,
    replacement: " \\mathbin{\\&} ",
    enabled: false,
  },
  {
    id: "sym/bitwise-or",
    group: "sym",
    descriptionKey: "rule.sym/bitwise-or",
    pattern: /(?<![|\\])\|(?![|=])/g,
    replacement: " \\mid ",
    enabled: false,
  },
  {
    id: "sym/bitwise-xor",
    group: "sym",
    descriptionKey: "rule.sym/bitwise-xor",
    pattern: /(?<![\\{a-zA-Z])xor(?![a-zA-Z}])/g,
    replacement: " \\oplus ",
    enabled: true,
  },
  {
    id: "sym/plus-minus",
    group: "sym",
    descriptionKey: "rule.sym/plus-minus",
    pattern: /\+-/g,
    replacement: " \\pm ",
    enabled: true,
  },
  {
    id: "sym/approx",
    group: "sym",
    descriptionKey: "rule.sym/approx",
    pattern: /~=/g,
    replacement: " \\approx ",
    enabled: true,
  },
  {
    id: "sym/infinity",
    group: "sym",
    descriptionKey: "rule.sym/infinity",
    pattern: /(?<![a-zA-Z\\])(INF|inf)(?![a-zA-Z])/g,
    replacement: " \\infty ",
    enabled: true,
  },
  {
    id: "sym/floor-div",
    group: "sym",
    descriptionKey: "rule.sym/floor-div",
    pattern: /\/\//g,
    replacement: " \\div ",
    enabled: true,
  },
  {
    id: "fn/gcd",
    group: "fn",
    descriptionKey: "rule.fn/gcd",
    pattern: /(?<![\\{a-zA-Z])gcd(?![a-zA-Z}])/g,
    replacement: " \\gcd ",
    enabled: true,
  },
  {
    id: "fn/min",
    group: "fn",
    descriptionKey: "rule.fn/min",
    pattern: /(?<![\\{a-zA-Z])min(?![a-zA-Z}])/g,
    replacement: " \\min ",
    enabled: true,
  },
  {
    id: "fn/max",
    group: "fn",
    descriptionKey: "rule.fn/max",
    pattern: /(?<![\\{a-zA-Z])max(?![a-zA-Z}])/g,
    replacement: " \\max ",
    enabled: true,
  },
  {
    id: "fn/log",
    group: "fn",
    descriptionKey: "rule.fn/log",
    pattern: /(?<![\\{a-zA-Z])log(?![a-zA-Z}])/g,
    replacement: " \\log ",
    enabled: true,
  },
  {
    id: "fn/lca",
    group: "fn",
    descriptionKey: "rule.fn/lca",
    pattern: /(?<!\\operatorname\{)LCA(?!\})/g,
    replacement: " \\operatorname{LCA}",
    enabled: true,
  },
  {
    id: "fn/lcm",
    group: "fn",
    descriptionKey: "rule.fn/lcm",
    pattern: /(?<!\\operatorname\{)lcm(?!\})/g,
    replacement: " \\operatorname{lcm}",
    enabled: true,
  },
  {
    id: "fn/mex",
    group: "fn",
    descriptionKey: "rule.fn/mex",
    pattern: /(?<!\\operatorname\{)MEX(?!\})/g,
    replacement: " \\operatorname{MEX}",
    enabled: true,
  },
  {
    id: "fn/sin",
    group: "fn",
    descriptionKey: "rule.fn/sin",
    pattern: /(?<![\\{a-zA-Z])sin(?![a-zA-Z}])/g,
    replacement: " \\sin ",
    enabled: true,
  },
  {
    id: "fn/cos",
    group: "fn",
    descriptionKey: "rule.fn/cos",
    pattern: /(?<![\\{a-zA-Z])cos(?![a-zA-Z}])/g,
    replacement: " \\cos ",
    enabled: true,
  },
  {
    id: "fn/tan",
    group: "fn",
    descriptionKey: "rule.fn/tan",
    pattern: /(?<![\\{a-zA-Z])tan(?![a-zA-Z}])/g,
    replacement: " \\tan ",
    enabled: true,
  },
  {
    id: "fn/ln",
    group: "fn",
    descriptionKey: "rule.fn/ln",
    pattern: /(?<![\\{a-zA-Z])ln(?![a-zA-Z}])/g,
    replacement: " \\ln ",
    enabled: true,
  },
  {
    id: "fn/exp",
    group: "fn",
    descriptionKey: "rule.fn/exp",
    pattern: /(?<![\\{a-zA-Z])exp(?![a-zA-Z}])/g,
    replacement: " \\exp ",
    enabled: true,
  },
  {
    id: "fn/sqrt",
    group: "fn",
    descriptionKey: "rule.fn/sqrt",
    pattern: /(?<![\\{a-zA-Z])sqrt(?![a-zA-Z}])/g,
    replacement: " \\sqrt",
    enabled: true,
  },
  {
    id: "fn/mod",
    group: "fn",
    descriptionKey: "rule.fn/mod",
    pattern: /(?<![\\{a-zA-Z])mod(?![a-zA-Z}])/g,
    replacement: " \\bmod ",
    enabled: true,
  },
  {
    id: "fn/xor",
    group: "fn",
    descriptionKey: "rule.fn/xor",
    pattern: /(?<!\\operatorname\{)XOR(?!\})/g,
    replacement: " \\operatorname{XOR}",
    enabled: true,
  },
  {
    id: "fn/dis",
    group: "fn",
    descriptionKey: "rule.fn/dis",
    pattern: /(?<![\\{a-zA-Z])dis(?:t)?(?![a-zA-Z}])/g,
    replacement: " \\operatorname{dis}",
    enabled: true,
  },
  {
    id: "fn/deg",
    group: "fn",
    descriptionKey: "rule.fn/deg",
    pattern: /(?<![\\{a-zA-Z])deg(?![a-zA-Z}])/g,
    replacement: " \\deg ",
    enabled: true,
  },
  {
    id: "fn/sgn",
    group: "fn",
    descriptionKey: "rule.fn/sgn",
    pattern: /(?<![\\{a-zA-Z])sgn(?![a-zA-Z}])/g,
    replacement: " \\operatorname{sgn}",
    enabled: true,
  },
  {
    id: "fn/rank",
    group: "fn",
    descriptionKey: "rule.fn/rank",
    pattern: /(?<![\\{a-zA-Z])rank(?![a-zA-Z}])/g,
    replacement: " \\operatorname{rank}",
    enabled: true,
  },
  {
    id: "fn/popcount",
    group: "fn",
    descriptionKey: "rule.fn/popcount",
    pattern: /(?<![\\{a-zA-Z])popcount(?![a-zA-Z}])/g,
    replacement: " \\operatorname{popcount}",
    enabled: true,
  },
  {
    id: "fn/lowbit",
    group: "fn",
    descriptionKey: "rule.fn/lowbit",
    pattern: /(?<![\\{a-zA-Z])lowbit(?![a-zA-Z}])/g,
    replacement: " \\operatorname{lowbit}",
    enabled: true,
  },
  {
    id: "syn/array-to-subscript",
    group: "syn",
    descriptionKey: "rule.syn/array-to-subscript",
    pattern: /(?<!\\)(?<![a-zA-Z])([a-zA-Z]+)((?:\[[^\]]+\])+)/g,
    replacement: (_m: string, name: string, brackets: string) => {
      const indices = brackets
        .replace(/^\[|\]$/g, "")
        .split("][")
        .join(",");
      return `${name}_{${indices}}`;
    },
    enabled: false,
  },
  {
    id: "syn/superscript-pow",
    group: "syn",
    descriptionKey: "rule.syn/superscript-pow",
    pattern: /[ \t]*\^[ \t]*/g,
    replacement: "^",
    enabled: true,
  },
  {
    id: "syn/abs-to-bracket",
    group: "syn",
    descriptionKey: "rule.syn/abs-to-bracket",
    pattern: /(?<![\\a-zA-Z])abs\(([^)]*)\)/g,
    replacement: (_: string, inner: string) => `\\lvert ${inner.trim()} \\rvert`,
    enabled: true,
  },
  {
    id: "syn/ceil-floor",
    group: "syn",
    descriptionKey: "rule.syn/ceil-floor",
    pattern: /(?<![\\a-zA-Z])(ceil|floor)\(([^)]*)\)/g,
    replacement: (_: string, fn: string, inner: string) =>
      fn === "ceil"
        ? `\\lceil ${inner.trim()} \\rceil`
        : `\\lfloor ${inner.trim()} \\rfloor`,
    enabled: true,
  },
];

export function getDefaultMathRules(): Record<string, boolean> {
  // Engine-side default: all rules are active (matches the original's default
  // when no `enabledRules.math` array is passed).
  const rules: Record<string, boolean> = {};
  for (const rule of MATH_RULES) {
    rules[rule.id] = true;
  }
  return rules;
}

export function getEnabledRules(ruleConfig: Record<string, boolean>): MathRule[] {
  return MATH_RULES.filter((r) => ruleConfig[r.id]);
}
